version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: backend
      MYSQL_USER: example
      MYSQL_PASSWORD: example

volumes:
  db_data:
